# ironworker configuration file
ironworker:
  # IF-MAP connection settings
  ifmap:
    # connection uses a thread-safe SSRC
    threadsafe: true
    # maximum time in milliseconds for initial connection
    initialconnectiontimeout: 120000
    # Authentication based configuration
    authentication:
      # Selected authentication scheme; possible are basic or cert
      method: basic
      # Configuration of basic authentication scheme
      basic:
        # URL of the MAP server
        url: https://127.0.0.1:8443
        # Basic authentication username
        username: ironworker
        # Basic authentication password
        password: ironworker
      # Configuration of certificate-based authentication scheme
      cert:
        # URL of the MAP server
        url: https://127.0.0.1:8444
      # Truststore configuration
      truststore:
        # path and filename of the keystore
        path: /keystore/ironworker.jks
        # password of the keystore
        password: ironworker
